import type { BodyAbilityV1Def } from '../../types/bodyAbilityV1';

/** Future roadmap abilities — text + glyph placeholders only; not unlockable in v1. */
export const BODY_ABILITY_FUTURE_CATALOG: BodyAbilityV1Def[] = [
  // Group II — Устойчивая форма
  {
    id: 'walk_without_planning',
    title: 'Проще выйти пройтись без долгой подготовки',
    description: 'Движение становится менее тяжёлым решением и чаще начинается спокойно.',
    category: 'mobility',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🚶',
  },
  {
    id: 'longer_standing_tasks',
    title: 'Легче делать дела стоя',
    description: 'Обычные дела стоя начинают требовать меньше внутреннего усилия.',
    category: 'dailyLife',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🧍',
  },
  {
    id: 'less_joint_pressure',
    title: 'Меньше ощущения давления в суставах',
    description: 'Тело мягче переносит нагрузку, а движение ощущается спокойнее.',
    category: 'recovery',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '◉',
  },
  {
    id: 'smoother_morning_start',
    title: 'Проще начать движение утром',
    description: 'Утренний старт становится менее тяжёлым, маршрут начинается мягче.',
    category: 'recovery',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🌅',
  },
  {
    id: 'better_pace_control',
    title: 'Легче держать ровный темп',
    description: 'Шаг становится спокойнее, темп — устойчивее, путь — ровнее.',
    category: 'endurance',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '▲',
  },
  {
    id: 'less_after_walk_fatigue',
    title: 'Меньше усталости после прогулки',
    description: 'После маршрута остаётся больше ресурса на день.',
    category: 'endurance',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🗺️',
  },
  {
    id: 'easier_shower_routine',
    title: 'Проще проходить утренние ритуалы',
    description: 'Бытовые действия становятся менее тяжёлыми и более предсказуемыми.',
    category: 'dailyLife',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '⌂',
  },
  {
    id: 'easier_bag_carrying',
    title: 'Легче нести сумку или покупки',
    description: 'Повседневная нагрузка меньше выбивает из маршрута.',
    category: 'strength',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🎒',
  },
  {
    id: 'better_balance',
    title: 'Больше устойчивости в движении',
    description: 'Тело увереннее держит равновесие в обычных перемещениях.',
    category: 'mobility',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '◈',
  },
  {
    id: 'calmer_evening_body',
    title: 'Тело спокойнее к вечеру',
    description: 'В конце дня остаётся меньше тяжести и больше ощущения контроля.',
    category: 'recovery',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🌙',
  },
  {
    id: 'easier_public_routes',
    title: 'Проще проходить маршруты вне дома',
    description: 'Дороги, магазины и дела вне дома становятся менее тревожными.',
    category: 'confidence',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '✦',
  },
  {
    id: 'waist_freedom',
    title: 'Больше свободы в области талии',
    description: 'Посадка одежды и движения корпуса ощущаются свободнее.',
    category: 'clothing',
    tier: 'middle',
    progressionRing: 'stable_form',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '◆',
  },
  // Group III — Новая мобильность
  {
    id: 'choose_longer_route',
    title: 'Можно выбрать маршрут длиннее',
    description: 'Длинный путь становится не угрозой, а вариантом.',
    category: 'endurance',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🗺️',
  },
  {
    id: 'stairs_without_pause',
    title: 'Лестница даётся без обязательной паузы',
    description: 'Подъём уже не требует заранее готовиться к остановке.',
    category: 'endurance',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '⬆️',
  },
  {
    id: 'active_day_capacity',
    title: 'Проще выдержать активный день',
    description: 'День с делами и движением становится более управляемым.',
    category: 'endurance',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '▲',
  },
  {
    id: 'travel_comfort',
    title: 'Дорога и поездки ощущаются легче',
    description: 'Путь, посадка, выход и ожидание требуют меньше ресурса.',
    category: 'dailyLife',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🚗',
  },
  {
    id: 'clothing_choice_confidence',
    title: 'Больше уверенности при выборе одежды',
    description: 'Одежда становится не проверкой, а способом почувствовать себя лучше.',
    category: 'clothing',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '👕',
  },
  {
    id: 'body_trust',
    title: 'Больше доверия к телу',
    description: 'Тело чаще отвечает устойчивостью, а не тревогой.',
    category: 'confidence',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '✨',
  },
  {
    id: 'movement_without_shame',
    title: 'Движение без лишнего стеснения',
    description: 'Двигаться становится проще не только физически, но и внутренне.',
    category: 'confidence',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '✦',
  },
  {
    id: 'recovery_self_control',
    title: 'Легче вовремя заметить перегруз',
    description: 'Возврат начинается раньше, до полного проседания ресурса.',
    category: 'recovery',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🔋',
  },
  {
    id: 'stable_week_body',
    title: 'Тело стабильнее держит неделю',
    description: 'Неровная неделя уже не сбивает весь маршрут.',
    category: 'recovery',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '📅',
  },
  {
    id: 'strength_in_daily_life',
    title: 'Больше силы в обычных делах',
    description: 'Повседневные действия начинают ощущаться как подтверждение силы.',
    category: 'strength',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '💪',
  },
  {
    id: 'free_movement_identity',
    title: 'Движение становится частью новой жизни',
    description: 'Активность перестаёт быть отдельным заданием и входит в образ жизни.',
    category: 'confidence',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '🧭',
  },
  {
    id: 'new_body_baseline',
    title: 'Новое тело становится нормой',
    description: 'То, что раньше казалось трудным, становится обычной частью дня.',
    category: 'confidence',
    tier: 'late',
    progressionRing: 'new_mobility',
    availability: 'future',
    artStatus: 'placeholder',
    unlockMode: 'manual',
    hint: '',
    hintSignals: [],
    icon: '⭐',
  },
];
