import type { Achievement, AchievementCategory, AchievementTier } from '../types/achievements';

export const ACHIEVEMENT_TIERS = {
  bronze: {
    label: 'Бронза',
    color: 'from-orange-700 to-amber-500',
    borderColor: 'border-amber-600',
  },
  silver: {
    label: 'Серебро',
    color: 'from-slate-400 to-slate-100',
    borderColor: 'border-slate-300',
  },
  gold: {
    label: 'Золото',
    color: 'from-yellow-500 to-amber-200',
    borderColor: 'border-yellow-400',
  },
  epic: {
    label: 'Эпик',
    color: 'from-purple-700 to-fuchsia-400',
    borderColor: 'border-purple-500',
  },
  legendary: {
    label: 'Легендарная',
    color: 'from-red-700 via-orange-500 to-yellow-300',
    borderColor: 'border-orange-400',
  },
} as const;

export const CATEGORY_LABELS: Record<AchievementCategory, string> = {
  start: 'Старт',
  weight: 'Вес',
  measurements: 'Замеры',
  calories: 'Калории',
  steps: 'Шаги',
  alcohol: 'Алкоголь',
  training: 'Тренировки',
  journal: 'Дневник',
  life: 'Жизнь',
  combo: 'Комбо',
  boss: 'Боссы',
  recovery: 'Восстановление',
  momentum: 'Инерция',
  xp: 'XP',
};

export const ICON_EMOJI_MAP: Record<string, string> = {
  'first-step': '👣',
  'three-days': '📅',
  'first-week': '🗓️',
  'habit-installed': '🏛️',
  'weight-minus-1': '⚖️',
  'weight-minus-5': '🪶',
  'weight-minus-10': '🔥',
  'weight-minus-15': '📉',
  'weight-minus-20': '🏔️',
  'weight-minus-30': '💎',
  'weight-minus-50': '🌅',
  'measurements-first': '📏',
  'monday-control': '🌙',
  'measurements-4': '📊',
  'measurements-8': '📈',
  'measurements-12': '🎯',
  'waist-minus-1': '〰️',
  'waist-minus-5': '〰️',
  'waist-minus-10': '✂️',
  'waist-minus-20': '👗',
  'calories-first': '🍽️',
  'calories-ok': '✅',
  'calories-7': '🥗',
  'calories-14': '🥙',
  'calories-30': '🧘',
  'return-after-over': '↩️',
  'steps-first': '🚶',
  'steps-goal': '👟',
  'steps-7': '🏃',
  'steps-15': '🛤️',
  'steps-30': '🌄',
  'steps-100k': '💯',
  'steps-500k': '🛣️',
  'steps-1m': '🌍',
  'steps-20k-day': '🚶',
  'steps-30k-day': '🦌',
  'no-alcohol-1': '💧',
  'no-alcohol-7': '🧠',
  'no-alcohol-10': '🌿',
  'no-alcohol-15': '☀️',
  'no-alcohol-20': '🛡️',
  'no-alcohol-30': '🌕',
  'no-alcohol-60': '💫',
  'no-alcohol-90': '👑',
  'sober-weekend': '🎉',
  'return-next-day': '🔄',
  'exercise-first': '☀️',
  'exercise-10': '💪',
  'exercise-50': '🔆',
  'exercise-100': '⚡',
  'gym-first': '🏋️',
  'gym-week': '📆',
  'gym-4-weeks': '🗓️',
  'gym-12-weeks': '🛡️',
  'gym-50': '🏆',
  'journal-first': '✍️',
  'journal-7': '📝',
  'journal-30': '📔',
  'journal-100': '📚',
  'cooking-first': '🍳',
  'cooking-month': '🥘',
  'repair-first': '🔧',
  'repair-30': '🏠',
  'plants-first': '🌱',
  'plants-30': '🪴',
  'hobby-first': '🎨',
  'hobby-30': '🎭',
  'good-day': '⭐',
  'great-day': '🌟',
  'hero-day': '🦸',
  'iron-day': '⚔️',
  'balance-day': '⚖️',
  'strong-week': '📣',
  'hero-week': '🦹',
  'perfect-base': '🏆',
  'back-after-bad-day': '💥',
  'back-in-game': '🎮',
  'xp-500': '✨',
  'xp-1200': '🌠',
  'xp-3500': '🔮',
  'xp-10000': '🚀',
  'xp-30000': '🔥',
  'xp-100000': '👑',
  'boss-first': '👹',
  'boss-perfect': '✨',
  'boss-3-streak': '🔥',
  'boss-month': '👑',
  'recovery-minimal': '🛡️',
  'minimal-day-completed': '🛡️',
  'recovery-not-robot': '🤝',
  'recovery-heard': '🔋',
  'energy-low-first': '🔋',
  'recovery-smart': '🌿',
  'not-a-robot': '🤖',
  'balance-of-strength': '⚖️',
  'steps-min-7': '👣',
  'steps-minimum-week': '👣',
  'steps-norm-7': '🥾',
  'steps-normal-week': '🥾',
  'steps-excellent': '🏅',
  'steps-excellent-day': '🏅',
  'steps-week-5': '🛤️',
  'steps-strong-week': '🛤️',
  'momentum-start': '⚙️',
  'momentum-stable': '🟢',
  'momentum-boost': '🔥',
  'momentum-flow': '🌊',
  'momentum-return': '🔁',
};

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'start_first_entry', title: 'Первый шаг', description: 'Внести первые данные за день', category: 'start', tier: 'bronze', iconKey: 'first-step', conditionType: 'instant' },
  { id: 'start_three_days', title: 'Я здесь всерьез', description: 'Заполнить данные 3 дня подряд', category: 'start', tier: 'bronze', iconKey: 'three-days', conditionType: 'streak', target: 3 },
  { id: 'start_first_week', title: 'Первая сводка', description: 'Завершить первую неделю в приложении', category: 'start', tier: 'silver', iconKey: 'first-week', conditionType: 'weekly', target: 1 },
  { id: 'start_30_days', title: 'Привычка установлена', description: 'Вести приложение 30 дней', category: 'start', tier: 'gold', iconKey: 'habit-installed', conditionType: 'total', target: 30 },

  { id: 'weight_minus_1', title: 'Минус первый', description: 'Сбросить 1 кг от стартового веса', category: 'weight', tier: 'bronze', iconKey: 'weight-minus-1', conditionType: 'milestone', target: 1 },
  { id: 'weight_minus_5', title: 'Пять кило позади', description: 'Сбросить 5 кг от стартового веса', category: 'weight', tier: 'bronze', iconKey: 'weight-minus-5', conditionType: 'milestone', target: 5 },
  { id: 'weight_minus_10', title: 'Десятка снята', description: 'Сбросить 10 кг от стартового веса', category: 'weight', tier: 'silver', iconKey: 'weight-minus-10', conditionType: 'milestone', target: 10 },
  { id: 'weight_minus_15', title: 'Минус пятнадцать', description: 'Сбросить 15 кг от стартового веса', category: 'weight', tier: 'silver', iconKey: 'weight-minus-15', conditionType: 'milestone', target: 15 },
  { id: 'weight_minus_20', title: 'Двадцатка пройдена', description: 'Сбросить 20 кг от стартового веса', category: 'weight', tier: 'gold', iconKey: 'weight-minus-20', conditionType: 'milestone', target: 20 },
  { id: 'weight_minus_30', title: 'Тридцатый рубеж', description: 'Сбросить 30 кг от стартового веса', category: 'weight', tier: 'epic', iconKey: 'weight-minus-30', conditionType: 'milestone', target: 30 },
  { id: 'weight_minus_50', title: 'Новая глава', description: 'Сбросить 50 кг от стартового веса', category: 'weight', tier: 'legendary', iconKey: 'weight-minus-50', conditionType: 'milestone', target: 50 },

  { id: 'measurements_first', title: 'Точка отсчета', description: 'Впервые внести вес и замеры', category: 'measurements', tier: 'bronze', iconKey: 'measurements-first', conditionType: 'instant' },
  { id: 'measurements_monday', title: 'Понедельник контроля', description: 'Внести замеры в понедельник', category: 'measurements', tier: 'bronze', iconKey: 'monday-control', conditionType: 'instant' },
  { id: 'measurements_4_weeks', title: 'Месяц наблюдений', description: 'Внести 4 еженедельных замера', category: 'measurements', tier: 'silver', iconKey: 'measurements-4', conditionType: 'total', target: 4 },
  { id: 'measurements_8_weeks', title: 'Стабильный контроль', description: 'Внести 8 еженедельных замеров', category: 'measurements', tier: 'silver', iconKey: 'measurements-8', conditionType: 'total', target: 8 },
  { id: 'measurements_12_weeks', title: 'Долгая дистанция', description: 'Внести 12 еженедельных замеров', category: 'measurements', tier: 'gold', iconKey: 'measurements-12', conditionType: 'total', target: 12 },
  { id: 'waist_minus_1', title: 'Первый сантиметр', description: 'Уменьшить талию на 1 см от старта', category: 'measurements', tier: 'bronze', iconKey: 'waist-minus-1', conditionType: 'milestone', target: 1 },
  { id: 'waist_minus_5', title: 'Минус пять на талии', description: 'Уменьшить талию на 5 см от старта', category: 'measurements', tier: 'silver', iconKey: 'waist-minus-5', conditionType: 'milestone', target: 5 },
  { id: 'waist_minus_10', title: 'Десять сантиметров', description: 'Уменьшить талию на 10 см от старта', category: 'measurements', tier: 'gold', iconKey: 'waist-minus-10', conditionType: 'milestone', target: 10 },
  { id: 'waist_minus_20', title: 'Силуэт меняется', description: 'Уменьшить талию на 20 см от старта', category: 'measurements', tier: 'legendary', iconKey: 'waist-minus-20', conditionType: 'milestone', target: 20 },

  { id: 'calories_first', title: 'Первый подсчет', description: 'Впервые внести калории', category: 'calories', tier: 'bronze', iconKey: 'calories-first', conditionType: 'instant' },
  { id: 'calories_first_ok', title: 'Попал в лимит', description: 'Первый день с калориями в лимите', category: 'calories', tier: 'bronze', iconKey: 'calories-ok', conditionType: 'instant' },
  { id: 'calories_7_streak', title: 'Неделя в рамках', description: '7 дней подряд попадать в лимит калорий', category: 'calories', tier: 'silver', iconKey: 'calories-7', conditionType: 'streak', target: 7 },
  { id: 'calories_14_streak', title: 'Две недели дисциплины', description: '14 дней подряд попадать в лимит калорий', category: 'calories', tier: 'gold', iconKey: 'calories-14', conditionType: 'streak', target: 14 },
  { id: 'calories_30_streak', title: 'Месяц контроля', description: '30 дней подряд попадать в лимит калорий', category: 'calories', tier: 'epic', iconKey: 'calories-30', conditionType: 'streak', target: 30 },
  { id: 'calories_return_after_over', title: 'Не сорвался после перебора', description: 'На следующий день после превышения снова попасть в лимит', category: 'calories', tier: 'silver', iconKey: 'return-after-over', conditionType: 'combo' },

  { id: 'steps_first', title: 'Вышел из дома', description: 'Впервые внести шаги', category: 'steps', tier: 'bronze', iconKey: 'steps-first', conditionType: 'instant' },
  { id: 'steps_first_goal', title: 'Норма достигнута', description: 'Первый день с нормой по шагам (11500+)', category: 'steps', tier: 'bronze', iconKey: 'steps-goal', conditionType: 'instant' },
  { id: 'steps_minimum_7_streak', title: 'Минимум удержан', description: '7 дней подряд 7000+ шагов', category: 'steps', tier: 'silver', iconKey: 'steps-min-7', conditionType: 'streak', target: 7 },
  { id: 'steps_normal_7_streak', title: 'Неделя нормы', description: '7 дней подряд 11500+ шагов', category: 'steps', tier: 'gold', iconKey: 'steps-norm-7', conditionType: 'streak', target: 7 },
  { id: 'steps_excellent_first', title: 'Отличный ход', description: 'Первый день 14000+ шагов', category: 'steps', tier: 'silver', iconKey: 'steps-excellent', conditionType: 'instant' },
  { id: 'steps_normal_5_week', title: 'Сильная неделя движения', description: '5 дней за неделю с нормой 11500+ шагов', category: 'steps', tier: 'silver', iconKey: 'steps-week-5', conditionType: 'streak', target: 5 },
  { id: 'steps_7_streak', title: 'Неделя на ногах', description: '7 дней подряд норма по шагам (11500+)', category: 'steps', tier: 'silver', iconKey: 'steps-7', conditionType: 'streak', target: 7 },
  { id: 'steps_15_streak', title: '15 дней на ходу', description: '15 дней подряд норма по шагам (11500+)', category: 'steps', tier: 'gold', iconKey: 'steps-15', conditionType: 'streak', target: 15 },
  { id: 'steps_30_streak', title: 'Месяц движения', description: '30 дней подряд норма по шагам (11500+)', category: 'steps', tier: 'epic', iconKey: 'steps-30', conditionType: 'streak', target: 30 },
  { id: 'steps_100k_total', title: '100 тысяч шагов', description: 'Набрать 100 000 шагов за все время', category: 'steps', tier: 'bronze', iconKey: 'steps-100k', conditionType: 'total', target: 100000 },
  { id: 'steps_500k_total', title: 'Полмиллиона', description: 'Набрать 500 000 шагов за все время', category: 'steps', tier: 'silver', iconKey: 'steps-500k', conditionType: 'total', target: 500000 },
  { id: 'steps_1m_total', title: 'Миллион шагов', description: 'Набрать 1 000 000 шагов за все время', category: 'steps', tier: 'gold', iconKey: 'steps-1m', conditionType: 'total', target: 1000000 },
  { id: 'steps_20k_day', title: 'Шел, шел и дошел', description: 'Пройти 20 000+ шагов за день', category: 'steps', tier: 'silver', iconKey: 'steps-20k-day', conditionType: 'instant' },
  { id: 'steps_30k_day', title: 'Лось городского типа', description: 'Пройти 30 000+ шагов за день', category: 'steps', tier: 'gold', iconKey: 'steps-30k-day', conditionType: 'instant' },

  { id: 'alcohol_1_day', title: 'Чистый день', description: 'Провести 1 день без алкоголя', category: 'alcohol', tier: 'bronze', iconKey: 'no-alcohol-1', conditionType: 'streak', target: 1 },
  { id: 'alcohol_7_days', title: 'Неделя ясности', description: 'Провести 7 дней подряд без алкоголя', category: 'alcohol', tier: 'silver', iconKey: 'no-alcohol-7', conditionType: 'streak', target: 7 },
  { id: 'alcohol_10_days', title: '10 дней контроля', description: 'Провести 10 дней подряд без алкоголя', category: 'alcohol', tier: 'silver', iconKey: 'no-alcohol-10', conditionType: 'streak', target: 10 },
  { id: 'alcohol_15_days', title: '15 дней ясной головы', description: 'Провести 15 дней подряд без алкоголя', category: 'alcohol', tier: 'gold', iconKey: 'no-alcohol-15', conditionType: 'streak', target: 15 },
  { id: 'alcohol_20_days', title: '20 дней без отката', description: 'Провести 20 дней подряд без алкоголя', category: 'alcohol', tier: 'gold', iconKey: 'no-alcohol-20', conditionType: 'streak', target: 20 },
  { id: 'alcohol_30_days', title: 'Месяц без алкоголя', description: 'Провести 30 дней подряд без алкоголя', category: 'alcohol', tier: 'epic', iconKey: 'no-alcohol-30', conditionType: 'streak', target: 30 },
  { id: 'alcohol_60_days', title: '60 дней чисто', description: 'Провести 60 дней подряд без алкоголя', category: 'alcohol', tier: 'legendary', iconKey: 'no-alcohol-60', conditionType: 'streak', target: 60 },
  { id: 'alcohol_90_days', title: '90 дней ясности', description: 'Провести 90 дней подряд без алкоголя', category: 'alcohol', tier: 'legendary', iconKey: 'no-alcohol-90', conditionType: 'streak', target: 90 },
  { id: 'alcohol_sober_weekend', title: 'Трезвые выходные', description: 'Пятница, суббота и воскресенье без алкоголя', category: 'alcohol', tier: 'silver', iconKey: 'sober-weekend', conditionType: 'combo' },
  { id: 'alcohol_return_next_day', title: 'Вернулся сразу', description: 'После дня с алкоголем следующий день провести без алкоголя', category: 'alcohol', tier: 'bronze', iconKey: 'return-next-day', conditionType: 'combo' },

  { id: 'exercise_first', title: 'Разбудил тело', description: 'Сделать первую зарядку', category: 'training', tier: 'bronze', iconKey: 'exercise-first', conditionType: 'instant' },
  { id: 'exercise_10_total', title: '10 зарядок', description: 'Сделать 10 зарядок всего', category: 'training', tier: 'bronze', iconKey: 'exercise-10', conditionType: 'total', target: 10 },
  { id: 'exercise_50_total', title: '50 зарядок', description: 'Сделать 50 зарядок всего', category: 'training', tier: 'gold', iconKey: 'exercise-50', conditionType: 'total', target: 50 },
  { id: 'exercise_100_total', title: '100 зарядок', description: 'Сделать 100 зарядок всего', category: 'training', tier: 'epic', iconKey: 'exercise-100', conditionType: 'total', target: 100 },
  { id: 'gym_first', title: 'Первый заход в зал', description: 'Выполнить первую тренировку в зале', category: 'training', tier: 'bronze', iconKey: 'gym-first', conditionType: 'instant' },
  { id: 'gym_week_norm', title: 'Норма недели', description: 'Выполнить недельную норму зала', category: 'training', tier: 'silver', iconKey: 'gym-week', conditionType: 'weekly' },
  { id: 'gym_4_weeks', title: 'Месяц тренировок', description: 'Выполнить недельную норму зала 4 недели подряд', category: 'training', tier: 'gold', iconKey: 'gym-4-weeks', conditionType: 'streak', target: 4 },
  { id: 'gym_12_weeks', title: 'Железная привычка', description: 'Выполнить недельную норму зала 12 недель подряд', category: 'training', tier: 'legendary', iconKey: 'gym-12-weeks', conditionType: 'streak', target: 12 },
  { id: 'gym_50_total', title: '50 тренировок', description: 'Выполнить 50 тренировок всего', category: 'training', tier: 'gold', iconKey: 'gym-50', conditionType: 'total', target: 50 },

  { id: 'journal_first', title: 'Первая мысль', description: 'Сделать первую запись в дневник', category: 'journal', tier: 'bronze', iconKey: 'journal-first', conditionType: 'instant' },
  { id: 'journal_7_total', title: 'Неделя осознанности', description: 'Сделать 7 записей в дневник', category: 'journal', tier: 'silver', iconKey: 'journal-7', conditionType: 'total', target: 7 },
  { id: 'journal_30_total', title: '30 записей', description: 'Сделать 30 записей в дневник', category: 'journal', tier: 'silver', iconKey: 'journal-30', conditionType: 'total', target: 30 },
  { id: 'journal_100_total', title: '100 записей', description: 'Сделать 100 записей в дневник', category: 'journal', tier: 'epic', iconKey: 'journal-100', conditionType: 'total', target: 100 },

  { id: 'cooking_first', title: 'Домашняя еда', description: 'Отметить первый день с готовкой', category: 'life', tier: 'bronze', iconKey: 'cooking-first', conditionType: 'instant' },
  { id: 'cooking_20_month', title: 'Месяц домашней еды', description: 'Отметить 20 дней с готовкой за месяц', category: 'life', tier: 'gold', iconKey: 'cooking-month', conditionType: 'monthly', target: 20 },
  { id: 'repair_first', title: 'Первый саморез', description: 'Отметить первый день ремонта', category: 'life', tier: 'bronze', iconKey: 'repair-first', conditionType: 'instant' },
  { id: 'repair_30_total', title: 'Большая переделка', description: 'Отметить 30 дней ремонта всего', category: 'life', tier: 'epic', iconKey: 'repair-30', conditionType: 'total', target: 30 },
  { id: 'plants_first', title: 'Полил и не забыл', description: 'Отметить первый день ухода за растениями', category: 'life', tier: 'bronze', iconKey: 'plants-first', conditionType: 'instant' },
  { id: 'plants_30_total', title: 'Растения одобряют', description: 'Отметить 30 дней ухода за растениями', category: 'life', tier: 'gold', iconKey: 'plants-30', conditionType: 'total', target: 30 },
  { id: 'hobby_first', title: 'Время для себя', description: 'Отметить первый день хобби', category: 'life', tier: 'bronze', iconKey: 'hobby-first', conditionType: 'instant' },
  { id: 'hobby_30_total', title: 'Мастерская радости', description: 'Отметить 30 дней хобби', category: 'life', tier: 'gold', iconKey: 'hobby-30', conditionType: 'total', target: 30 },

  { id: 'combo_good_day', title: 'Хороший день', description: 'Набрать 70+ очков за день', category: 'combo', tier: 'bronze', iconKey: 'good-day', conditionType: 'instant' },
  { id: 'combo_great_day', title: 'Отличный день', description: 'Набрать 100+ очков за день', category: 'combo', tier: 'silver', iconKey: 'great-day', conditionType: 'instant' },
  { id: 'combo_hero_day', title: 'День героя', description: 'В один день: калории в лимите, шаги выполнены, алкоголя не было', category: 'combo', tier: 'silver', iconKey: 'hero-day', conditionType: 'combo' },
  { id: 'combo_iron_day', title: 'Железный день', description: 'В один день: калории в лимите, шаги выполнены, зал выполнен, алкоголя не было', category: 'combo', tier: 'gold', iconKey: 'iron-day', conditionType: 'combo' },
  { id: 'combo_balance_day', title: 'День баланса', description: 'В один день: калории в лимите, шаги выполнены, дневник и хобби отмечены', category: 'combo', tier: 'silver', iconKey: 'balance-day', conditionType: 'combo' },
  { id: 'combo_strong_week', title: 'Сильная неделя', description: 'Выполнить 100% недельной цели по очкам', category: 'combo', tier: 'gold', iconKey: 'strong-week', conditionType: 'weekly' },
  { id: 'combo_hero_week', title: 'Неделя героя', description: '100% недельной цели, норма зала и 5 дней калорий в лимите', category: 'combo', tier: 'epic', iconKey: 'hero-week', conditionType: 'weekly' },
  { id: 'combo_perfect_base', title: 'Идеальная база', description: '7 дней без алкоголя, 7 дней шаги выполнены, 7 дней калории в лимите', category: 'combo', tier: 'legendary', iconKey: 'perfect-base', conditionType: 'weekly' },
  { id: 'combo_back_after_bad_day', title: 'Без отката', description: 'После плохого дня набрать 70+ очков', category: 'combo', tier: 'silver', iconKey: 'back-after-bad-day', conditionType: 'combo' },
  { id: 'combo_back_after_absence', title: 'Снова в игре', description: 'Вернуться после 7 дней без записей', category: 'combo', tier: 'bronze', iconKey: 'back-in-game', conditionType: 'combo' },

  { id: 'boss_first_defeat', title: 'Первый босс', description: 'Победить первого недельного босса', category: 'boss', tier: 'bronze', iconKey: 'boss-first', conditionType: 'instant' },
  { id: 'boss_perfect_win', title: 'Идеальная победа', description: 'Получить идеальную победу над боссом недели', category: 'boss', tier: 'gold', iconKey: 'boss-perfect', conditionType: 'instant' },
  { id: 'boss_3_streak', title: 'Три босса подряд', description: 'Победить 3 недельных босса подряд', category: 'boss', tier: 'silver', iconKey: 'boss-3-streak', conditionType: 'streak', target: 3 },
  { id: 'boss_4_streak', title: 'Месяц побед', description: 'Победить 4 недельных босса подряд', category: 'boss', tier: 'epic', iconKey: 'boss-month', conditionType: 'streak', target: 4 },

  { id: 'recovery_minimal_day', title: 'День удержан', description: 'Выполнить минимальный день', category: 'recovery', tier: 'bronze', iconKey: 'recovery-minimal', conditionType: 'instant' },
  { id: 'recovery_heard_body', title: 'Услышал тело', description: 'Впервые отметить низкий ресурс или восстановление', category: 'recovery', tier: 'bronze', iconKey: 'recovery-heard', conditionType: 'instant' },
  { id: 'recovery_smart', title: 'Восстановился грамотно', description: 'День восстановления/минимальный с калориями и без алкоголя', category: 'recovery', tier: 'silver', iconKey: 'recovery-smart', conditionType: 'instant' },
  { id: 'recovery_not_robot', title: 'Не робот, но стараюсь', description: 'После слабой недели выполнить 60% следующей', category: 'recovery', tier: 'silver', iconKey: 'recovery-not-robot', conditionType: 'combo' },
  { id: 'recovery_not_a_robot', title: 'Не робот, но в игре', description: '5 дней восстановления без потери серии учёта', category: 'recovery', tier: 'gold', iconKey: 'not-a-robot', conditionType: 'streak', target: 5 },
  { id: 'recovery_balance_of_strength', title: 'Баланс силы', description: '4 недели подряд: есть тренировки и хотя бы один день восстановления', category: 'combo', tier: 'epic', iconKey: 'balance-of-strength', conditionType: 'streak', target: 4 },

  { id: 'momentum_first_positive', title: 'Система сдвинулась', description: 'Впервые выйти из отрицательной инерции в 0+', category: 'momentum', tier: 'bronze', iconKey: 'momentum-start', conditionType: 'instant' },
  { id: 'momentum_stable', title: 'Стабильный ход', description: 'Впервые достичь инерции +10', category: 'momentum', tier: 'silver', iconKey: 'momentum-stable', conditionType: 'instant' },
  { id: 'momentum_boost', title: 'Хороший разгон', description: 'Впервые достичь инерции +40', category: 'momentum', tier: 'gold', iconKey: 'momentum-boost', conditionType: 'instant' },
  { id: 'momentum_flow', title: 'Поток', description: 'Впервые достичь инерции +70', category: 'momentum', tier: 'epic', iconKey: 'momentum-flow', conditionType: 'instant' },
  { id: 'momentum_return', title: 'Вернул ход', description: 'После потери хода подняться хотя бы до нейтральной зоны', category: 'momentum', tier: 'gold', iconKey: 'momentum-return', conditionType: 'instant' },

  { id: 'xp_500', title: 'Новичок системы', description: 'Набрать 500 XP', category: 'xp', tier: 'bronze', iconKey: 'xp-500', conditionType: 'milestone', target: 500 },
  { id: 'xp_1200', title: 'Уверенный старт', description: 'Набрать 1200 XP', category: 'xp', tier: 'bronze', iconKey: 'xp-1200', conditionType: 'milestone', target: 1200 },
  { id: 'xp_3500', title: 'Режим включен', description: 'Набрать 3500 XP', category: 'xp', tier: 'silver', iconKey: 'xp-3500', conditionType: 'milestone', target: 3500 },
  { id: 'xp_10000', title: 'Собранный человек', description: 'Набрать 10 000 XP', category: 'xp', tier: 'gold', iconKey: 'xp-10000', conditionType: 'milestone', target: 10000 },
  { id: 'xp_30000', title: 'Железный режим', description: 'Набрать 30 000 XP', category: 'xp', tier: 'epic', iconKey: 'xp-30000', conditionType: 'milestone', target: 30000 },
  { id: 'xp_100000', title: 'Легенда привычек', description: 'Набрать 100 000 XP', category: 'xp', tier: 'legendary', iconKey: 'xp-100000', conditionType: 'milestone', target: 100000 },
];

export const ACHIEVEMENT_BY_ID = Object.fromEntries(
  ACHIEVEMENTS.map((a) => [a.id, a]),
) as Record<string, Achievement>;

export function getTierLabel(tier: AchievementTier): string {
  return ACHIEVEMENT_TIERS[tier].label;
}
