import type {
  BodyAbilityDefinition,
  BodyAbilityDifficulty,
  BodyAbilityInterest,
  BodyAbilityKind,
  BodyAbilityUnlockMode,
  BodyPathType,
  WeightLossGoalBand,
  BodyAbilityBaselineEasy,
  BodyAbilityHiddenTopic,
} from '../types/bodyAbilityPersonal';

/** Bump when bank semantics / exclusions change in a way that should regenerate grids. */
export const BODY_ABILITY_BANK_VERSION = '2026.08.02-q1';

const ALL_BANDS: WeightLossGoalBand[] = [
  'under_10',
  '10_20',
  '20_50',
  '50_80',
  '80_plus',
];
const LIGHT: WeightLossGoalBand[] = ['under_10', '10_20'];
const MID: WeightLossGoalBand[] = ['10_20', '20_50'];
const HEAVY: WeightLossGoalBand[] = ['20_50', '50_80', '80_plus'];
const DEEP: WeightLossGoalBand[] = ['50_80', '80_plus'];
const SHAPE: WeightLossGoalBand[] = ['under_10', '10_20', '20_50'];

type Draft = Omit<BodyAbilityDefinition, 'scoreWeight' | 'kind'> & {
  scoreWeight?: number;
  kind?: BodyAbilityKind;
};

function inferKind(d: Draft): BodyAbilityKind {
  if (d.kind) return d.kind;
  if (
    d.tags.includes('weight') ||
    d.tags.includes('milestone') ||
    d.tags.includes('waist')
  ) {
    return 'milestone';
  }
  if (d.tags.includes('universal')) return 'route_mastery';
  if (d.unlockMode === 'auto' && d.autoUnlock) return 'route_mastery';
  if (
    d.category === 'mobility' ||
    d.category === 'daily_life' ||
    d.category === 'stairs_routes' ||
    d.category === 'flexibility'
  ) {
    return 'functional_change';
  }
  return 'body_change';
}

function def(d: Draft): BodyAbilityDefinition {
  return {
    scoreWeight: d.scoreWeight ?? 1,
    ...d,
    kind: inferKind(d),
  };
}

function weightMilestone(
  id: string,
  kg: number,
  bands: WeightLossGoalBand[],
  difficulty: BodyAbilityDifficulty,
): BodyAbilityDefinition {
  return def({
    id,
    title: `Весовой перевал −${kg} кг`,
    description: `Отмеченный рубеж снижения веса на ${kg} кг — один из сигналов пути, не единственный.`,
    category: 'measurements',
    goalBands: bands,
    pathTypes: ['shape_tuning', 'load_reduction', 'control_return', 'athlete_return'],
    unlockMode: 'auto',
    difficulty,
    kind: 'milestone',
    tags: ['weight', 'milestone'],
    hiddenByTopics: ['weight'],
    scoreWeight: 1.05,
    autoUnlock: { type: 'weight_loss_kg', target: kg },
  });
}

function waistMilestone(
  id: string,
  cm: number,
  bands: WeightLossGoalBand[],
  difficulty: BodyAbilityDifficulty,
): BodyAbilityDefinition {
  return def({
    id,
    title: `Талия −${cm} см`,
    description: `Замеры показывают изменение талии примерно на ${cm} см.`,
    category: 'measurements',
    secondaryCategories: ['appearance'],
    goalBands: bands,
    pathTypes: ['shape_tuning', 'appearance_focus'],
    unlockMode: 'auto',
    difficulty,
    kind: 'milestone',
    tags: ['waist', 'measurements', 'milestone'],
    hiddenByTopics: ['measurements', 'appearance'],
    scoreWeight: 1.05,
    autoUnlock: { type: 'waist_loss_cm', target: cm },
  });
}

export const BODY_ABILITY_BANK: BodyAbilityDefinition[] = [
  // ——— Appearance / silhouette (light–mid) ———
  def({
    id: 'clothes_fit_better',
    title: 'Одежда сидит свободнее',
    description: 'Привычные вещи ощущаются чуть свободнее в посадке.',
    category: 'appearance',
    goalBands: SHAPE,
    pathTypes: ['appearance_focus', 'shape_tuning'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['clothes', 'silhouette'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'silhouette_cleaner',
    title: 'Силуэт собраннее',
    description: 'В зеркале или на фото линия тела выглядит собраннее.',
    category: 'appearance',
    goalBands: LIGHT,
    pathTypes: ['appearance_focus', 'shape_tuning'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['silhouette'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'size_looser',
    title: 'Одежда на размер свободнее',
    description: 'Размер, который раньше сидел вплотную, стал свободнее.',
    category: 'appearance',
    goalBands: HEAVY,
    pathTypes: ['appearance_focus', 'shape_tuning', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['clothes', 'size'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'photo_progress',
    title: 'Фото-прогресс заметен',
    description: 'Сравнение фото показывает мягкое, но реальное изменение формы.',
    category: 'appearance',
    goalBands: SHAPE,
    pathTypes: ['appearance_focus', 'shape_tuning'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['photo'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'less_puffiness',
    title: 'Меньше тяжести и отёчности',
    description: 'Тело реже ощущается «залитым» к вечеру.',
    category: 'appearance',
    secondaryCategories: ['sleep_resource'],
    goalBands: LIGHT,
    pathTypes: ['resource_recovery', 'appearance_focus'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['puffiness'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'face_softer_load',
    title: 'Лицо выглядит спокойнее',
    description:
      'Субъективно лицо и общий вид кажутся спокойнее — это наблюдение, не обещание эффекта.',
    category: 'appearance',
    goalBands: LIGHT,
    pathTypes: ['appearance_focus'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['face'],
    hiddenByTopics: ['appearance'],
  }),

  // ——— Measurements ———
  waistMilestone('waist_minus_2', 2, LIGHT, 'early'),
  waistMilestone('waist_minus_5', 5, [...MID, ...DEEP], 'middle'),
  waistMilestone('waist_minus_10', 10, HEAVY, 'late'),
  waistMilestone('waist_minus_15', 15, DEEP, 'epic'),
  weightMilestone('weight_pass_2', 2, LIGHT, 'early'),
  weightMilestone('weight_pass_5', 5, [...LIGHT, '20_50'], 'early'),
  weightMilestone('weight_pass_10', 10, ALL_BANDS, 'middle'),
  weightMilestone('weight_pass_20', 20, HEAVY, 'middle'),
  weightMilestone('weight_pass_30', 30, HEAVY, 'late'),
  weightMilestone('weight_pass_40', 40, DEEP, 'late'),
  weightMilestone('weight_pass_50', 50, DEEP, 'epic'),
  def({
    id: 'measurements_shifted',
    title: 'Замеры сдвинулись',
    description: 'Хотя бы один замер тела изменился в нужную сторону.',
    category: 'measurements',
    goalBands: ALL_BANDS,
    pathTypes: ['shape_tuning', 'control_return'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['measurements'],
    hiddenByTopics: ['measurements'],
    autoUnlock: { type: 'waist_loss_cm', target: 1 },
  }),

  // ——— Endurance / walking ———
  def({
    id: 'walk_easier_short',
    title: 'Короткая прогулка даётся легче',
    description: 'Обычный короткий маршрут ощущается спокойнее.',
    category: 'endurance',
    goalBands: HEAVY,
    pathTypes: ['mobility_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['walk', 'beginner'],
    excludedByBaselineEasy: ['walk_10k', 'walk_15k'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'steps_10k_stable',
    title: 'Стабильные 10 тысяч шагов',
    description: 'Несколько дней с нормой шагов около 10 тысяч.',
    category: 'endurance',
    goalBands: [...MID, ...HEAVY],
    pathTypes: ['mobility_return', 'athlete_return'],
    unlockMode: 'auto',
    difficulty: 'middle',
    tags: ['walk', '10k', 'beginner'],
    excludedByBaselineEasy: ['walk_10k', 'walk_15k'],
    autoUnlock: { type: 'steps_days_normal', target: 5 },
  }),
  def({
    id: 'steps_12k_stable',
    title: 'Стабильные 12–14 тысяч шагов',
    description: 'Дни с более длинным маршрутом удерживаются без срыва ритма.',
    category: 'endurance',
    goalBands: HEAVY,
    pathTypes: ['mobility_return', 'athlete_return'],
    unlockMode: 'auto',
    difficulty: 'late',
    tags: ['walk', '12k'],
    excludedByBaselineEasy: ['walk_15k'],
    autoUnlock: { type: 'steps_days_normal', target: 10 },
  }),
  def({
    id: 'long_route_held',
    title: 'Длинный маршрут без отката',
    description:
      'Длинный маршрут или день с высокой нагрузкой удержан без срыва следующего дня.',
    category: 'endurance',
    secondaryCategories: ['sport_training'],
    goalBands: [...HEAVY],
    pathTypes: ['mobility_return', 'athlete_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'late',
    kind: 'body_change',
    tags: ['walk', 'long', 'endurance_high'],
  }),
  def({
    id: 'walk_as_base_not_goal',
    title: 'Шаги как база, не как подвиг',
    description: 'Движение снова часть дня, а не отдельная героическая цель.',
    category: 'endurance',
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return', 'control_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    kind: 'body_change',
    tags: ['walk', 'athlete'],
  }),
  def({
    id: 'evening_heaviness_less',
    title: 'Вечер переносится спокойнее',
    description:
      'После обычного дня тело реже просит полностью выключиться к вечеру.',
    category: 'endurance',
    secondaryCategories: ['sleep_resource'],
    goalBands: HEAVY,
    pathTypes: ['load_reduction', 'resource_recovery', 'athlete_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    kind: 'body_change',
    tags: ['fatigue', 'recovery_feel'],
  }),

  // ——— Stairs / routes ———
  def({
    id: 'stairs_easier',
    title: 'Лестница даётся легче',
    description: 'Подъём по лестнице ощущается спокойнее, чем раньше.',
    category: 'stairs_routes',
    goalBands: HEAVY,
    pathTypes: ['mobility_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['stairs'],
    excludedByBaselineEasy: ['stairs_ok'],
    hiddenByTopics: ['stairs'],
  }),
  def({
    id: 'stairs_as_stage',
    title: 'Лестница как этап, не как стена',
    description: 'Лестница перестала быть непреодолимым препятствием дня.',
    category: 'stairs_routes',
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['stairs'],
    excludedByBaselineEasy: ['stairs_ok'],
    hiddenByTopics: ['stairs'],
  }),
  def({
    id: 'route_without_pause',
    title: 'Маршрут без обязательной паузы',
    description: 'Знакомый путь пройден без вынужденной остановки «отдышаться».',
    category: 'stairs_routes',
    secondaryCategories: ['endurance'],
    goalBands: HEAVY,
    pathTypes: ['mobility_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['route'],
    hiddenByTopics: ['stairs', 'daily_life_limitations'],
  }),

  // ——— Deep mobility / daily life ———
  def({
    id: 'tie_shoes_easier',
    title: 'Легче завязывать обувь',
    description: 'Наклон и работа с обувью стали проще в быту.',
    category: 'flexibility',
    secondaryCategories: ['daily_life', 'mobility'],
    goalBands: DEEP,
    pathTypes: ['mobility_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['shoes', 'bend'],
    excludedByBaselineEasy: ['tie_shoes'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'stand_from_floor_easier',
    title: 'Легче вставать с пола',
    description: 'Подъём с низкой опоры даётся спокойнее.',
    category: 'mobility',
    secondaryCategories: ['daily_life'],
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['floor'],
    excludedByBaselineEasy: ['stand_from_floor'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'stand_longer_ok',
    title: 'Проще стоять дольше',
    description: 'Долгое стояние в быту переносится мягче.',
    category: 'mobility',
    goalBands: HEAVY,
    pathTypes: ['mobility_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['stand'],
    excludedByBaselineEasy: ['stand_long'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'car_seat_easier',
    title: 'Проще посадка в машину',
    description: 'Посадка и выход из машины ощущаются свободнее.',
    category: 'daily_life',
    goalBands: DEEP,
    pathTypes: ['mobility_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['car'],
    excludedByBaselineEasy: ['car_ok'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'chair_space_easier',
    title: 'Проще в кресле и пространстве',
    description: 'Повседневные посадки и тесные пространства даются спокойнее.',
    category: 'daily_life',
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['space'],
    excludedByBaselineEasy: ['car_ok', 'daily_chores_ok'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'chores_without_drain',
    title: 'Быт без выматывания',
    description: 'Обычные домашние дела оставляют больше ресурса.',
    category: 'daily_life',
    goalBands: HEAVY,
    pathTypes: ['load_reduction', 'mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['chores'],
    excludedByBaselineEasy: ['daily_chores_ok'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'legs_back_load_less',
    title: 'Тело легче переносит дневную нагрузку',
    description:
      'После обычного дня ноги и спина реже ощущаются перегруженными — наблюдение, не диагноз.',
    category: 'daily_life',
    secondaryCategories: ['endurance'],
    goalBands: DEEP,
    pathTypes: ['load_reduction', 'athlete_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'late',
    kind: 'body_change',
    tags: ['load', 'recovery_feel'],
    excludedByBaselineEasy: ['daily_chores_ok'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'get_up_easier',
    title: 'Вставать стало легче',
    description: 'Подъём с дивана или кровати ощущается проще.',
    category: 'mobility',
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['rise'],
    excludedByBaselineEasy: ['stand_from_floor', 'stand_long'],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'bend_easier',
    title: 'Наклоны даются мягче',
    description: 'Наклоны в быту стали спокойнее и увереннее.',
    category: 'flexibility',
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['bend'],
    excludedByBaselineEasy: ['tie_shoes'],
    hiddenByTopics: ['daily_life_limitations'],
  }),

  // ——— Nutrition ———
  def({
    id: 'nutrition_logged_week',
    title: 'Неделя учёта питания',
    description: 'Питание отмечалось несколько дней подряд — контроль вернулся.',
    category: 'nutrition_control',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'shape_tuning'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['nutrition'],
    excludedByBaselineEasy: ['nutrition_ok'],
    hiddenByTopics: ['nutrition'],
    autoUnlock: { type: 'calorie_tracking_days', target: 7 },
  }),
  def({
    id: 'nutrition_limit_streak',
    title: 'Питание в рамках несколько дней',
    description: 'Ритм питания удерживается без идеальности.',
    category: 'nutrition_control',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'auto',
    difficulty: 'middle',
    tags: ['nutrition', 'limit'],
    excludedByBaselineEasy: ['nutrition_ok'],
    hiddenByTopics: ['nutrition'],
    autoUnlock: { type: 'calorie_limit_days', target: 5 },
  }),
  def({
    id: 'less_evening_food_chaos',
    title: 'Меньше хаоса в вечернем питании',
    description: 'Вечерние решения стали спокойнее и честнее.',
    category: 'nutrition_control',
    secondaryCategories: ['alcohol_evening'],
    goalBands: LIGHT,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'early',
    tags: ['evening', 'nutrition'],
    hiddenByTopics: ['nutrition'],
  }),
  def({
    id: 'weekend_nutrition_held',
    title: 'Выходные по питанию удержаны',
    description: 'Выходные не размыли полностью ритм питания.',
    category: 'nutrition_control',
    goalBands: SHAPE,
    pathTypes: ['control_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['weekend', 'nutrition'],
    hiddenByTopics: ['nutrition'],
  }),
  def({
    id: 'nutrition_month_stable',
    title: 'Стабильный месяц питания',
    description: 'Учёт и ритм питания держатся около месяца.',
    category: 'nutrition_control',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'shape_tuning'],
    unlockMode: 'auto',
    difficulty: 'late',
    tags: ['nutrition', 'month'],
    hiddenByTopics: ['nutrition'],
    autoUnlock: { type: 'calorie_tracking_days', target: 24 },
  }),

  // ——— Alcohol / evening ———
  def({
    id: 'alcohol_free_week',
    title: 'Неделя ясных вечеров',
    description: 'Несколько дней подряд без алкоголя — вечер остаётся своим.',
    category: 'alcohol_evening',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['alcohol'],
    excludedByBaselineEasy: ['alcohol_ok'],
    hiddenByTopics: ['alcohol'],
    autoUnlock: { type: 'no_alcohol_days', target: 7 },
  }),
  def({
    id: 'alcohol_free_month',
    title: 'Месяц без алкогольного отката',
    description: 'Длинная серия ясных вечеров удержана.',
    category: 'alcohol_evening',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'auto',
    difficulty: 'late',
    tags: ['alcohol'],
    excludedByBaselineEasy: ['alcohol_ok'],
    hiddenByTopics: ['alcohol'],
    autoUnlock: { type: 'no_alcohol_days', target: 30 },
  }),
  def({
    id: 'evening_ritual_calm',
    title: 'Спокойный вечерний ритуал',
    description: 'Вечер закрывается мягче, без автоматического срыва.',
    category: 'alcohol_evening',
    secondaryCategories: ['sleep_resource'],
    goalBands: ALL_BANDS,
    pathTypes: ['resource_recovery', 'control_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['evening'],
    hiddenByTopics: ['alcohol'],
  }),
  def({
    id: 'return_after_evening_slip',
    title: 'Возврат после вечернего срыва',
    description: 'После сложного вечера маршрут снова отмечен без самоуничтожения.',
    category: 'alcohol_evening',
    secondaryCategories: ['confidence'],
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['return', 'alcohol'],
    hiddenByTopics: ['alcohol'],
  }),

  // ——— Sleep / resource ———
  def({
    id: 'sleep_marked_streak',
    title: 'Сон и ресурс отмечены',
    description: 'Несколько дней с отметкой сна или энергии.',
    category: 'sleep_resource',
    goalBands: ALL_BANDS,
    pathTypes: ['resource_recovery'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['sleep', 'resource'],
    autoUnlock: { type: 'sleep_or_energy_days', target: 5 },
  }),
  def({
    id: 'recovery_days_held',
    title: 'Восстановление без выпадения',
    description: 'Дни восстановления удержали путь, а не сломали его.',
    category: 'sleep_resource',
    goalBands: ALL_BANDS,
    pathTypes: ['resource_recovery', 'control_return'],
    unlockMode: 'auto',
    difficulty: 'middle',
    tags: ['recovery'],
    autoUnlock: { type: 'recovery_days', target: 3 },
  }),
  def({
    id: 'better_sleep_feel',
    title: 'Сон ощущается лучше',
    description: 'Субъективно сон стал глубже или спокойнее.',
    category: 'sleep_resource',
    goalBands: LIGHT,
    pathTypes: ['resource_recovery'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['sleep'],
  }),
  def({
    id: 'resource_after_load',
    title: 'Восстановление после нагрузки',
    description: 'После тяжёлого дня тело снова набирает ресурс через мягкий режим.',
    category: 'sleep_resource',
    secondaryCategories: ['sport_training'],
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return', 'resource_recovery'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['recovery', 'load'],
  }),

  // ——— Sport / strength / athlete ———
  def({
    id: 'training_week',
    title: 'Неделя тренировок',
    description: 'Тренировки снова появляются в неделе.',
    category: 'sport_training',
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['gym', 'athlete'],
    excludedByBaselineEasy: ['training_ok'],
    hiddenByTopics: ['sport'],
    autoUnlock: { type: 'gym_total', target: 2 },
  }),
  def({
    id: 'training_return_base',
    title: 'Спортивная база возвращается',
    description: 'Тренировки перестают быть редкой вспышкой.',
    category: 'sport_training',
    goalBands: HEAVY,
    pathTypes: ['athlete_return'],
    unlockMode: 'auto',
    difficulty: 'middle',
    tags: ['gym'],
    hiddenByTopics: ['sport'],
    autoUnlock: { type: 'gym_total', target: 8 },
  }),
  def({
    id: 'technique_returns',
    title: 'Техника возвращается',
    description: 'В движении снова появляется знакомая техника.',
    category: 'sport_training',
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['technique', 'athlete'],
    hiddenByTopics: ['sport'],
  }),
  def({
    id: 'strength_base',
    title: 'Силовая база чувствуется',
    description: 'В быту или тренировке ощущается возврат силы.',
    category: 'strength',
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['strength'],
    hiddenByTopics: ['sport'],
  }),
  def({
    id: 'body_responds_again',
    title: 'Тело снова отвечает',
    description: 'После нагрузки тело реагирует предсказуемее, чем в начале пути.',
    category: 'sport_training',
    secondaryCategories: ['confidence'],
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['athlete'],
    hiddenByTopics: ['sport'],
  }),
  def({
    id: 'stable_training_mode',
    title: 'Стабильный тренировочный режим',
    description: 'Тренировки встроены в ритм, а не держатся на мотивации.',
    category: 'sport_training',
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return', 'control_return'],
    unlockMode: 'auto',
    difficulty: 'late',
    tags: ['gym', 'streak'],
    hiddenByTopics: ['sport'],
    autoUnlock: { type: 'gym_total', target: 20 },
  }),
  def({
    id: 'physical_activity_counts',
    title: 'Физическая активность засчитывается',
    description: 'Тело работает не только шагами — нагрузка в деле тоже считается.',
    category: 'strength',
    secondaryCategories: ['daily_life'],
    goalBands: ALL_BANDS,
    pathTypes: ['load_reduction', 'athlete_return'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['physical_activity'],
  }),

  // ——— Control / confidence / habit ———
  def({
    id: 'habit_two_weeks',
    title: 'Привычка держится 2 недели',
    description: 'Базовый ритм удержан около двух недель.',
    category: 'confidence',
    goalBands: LIGHT,
    pathTypes: ['control_return', 'shape_tuning'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['habit', 'control'],
    autoUnlock: { type: 'calorie_tracking_days', target: 14 },
  }),
  def({
    id: 'stable_month',
    title: 'Стабильный месяц',
    description: 'Месяц возвращений и отметок — не идеальность, а устойчивость.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'auto',
    difficulty: 'late',
    tags: ['habit', 'month'],
    autoUnlock: { type: 'steps_days_minimum', target: 20 },
  }),
  def({
    id: 'weekend_held',
    title: 'Выходные удержаны',
    description: 'Выходные не обнулили маршрут полностью.',
    category: 'confidence',
    goalBands: SHAPE,
    pathTypes: ['control_return'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['weekend'],
  }),
  def({
    id: 'return_after_slip',
    title: 'Контроль после срыва',
    description: 'После сложного дня снова есть отметка — путь жив.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['return'],
  }),
  def({
    id: 'street_confidence',
    title: 'Увереннее на улице',
    description: 'Движение в городе ощущается спокойнее и свободнее.',
    category: 'confidence',
    secondaryCategories: ['mobility'],
    goalBands: HEAVY,
    pathTypes: ['mobility_return', 'appearance_focus'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['confidence'],
  }),
  def({
    id: 'tone_returns',
    title: 'Возвращается тонус',
    description: 'Тело ощущается собраннее и отзывчивее.',
    category: 'confidence',
    secondaryCategories: ['appearance'],
    goalBands: LIGHT,
    pathTypes: ['shape_tuning', 'athlete_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['tone'],
  }),
  def({
    id: 'movement_confidence',
    title: 'Уверенность в движении',
    description: 'Шаг и поворот тела даются с большим спокойствием.',
    category: 'confidence',
    secondaryCategories: ['mobility'],
    goalBands: ALL_BANDS,
    pathTypes: ['mobility_return', 'athlete_return'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['confidence', 'mobility'],
  }),

  // ——— Universal control/resource fallbacks ———
  def({
    id: 'minimal_day_valid',
    title: 'Минимальный день тоже считает',
    description: 'Понято на практике: маленький день удерживает путь.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['minimal', 'universal'],
    scoreWeight: 0.45,
    autoUnlock: { type: 'recovery_days', target: 1 },
  }),
  def({
    id: 'data_day_saved',
    title: 'День с данными сохранён',
    description: 'Появился честный след дня — система снова видит путь.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['universal', 'data'],
    scoreWeight: 0.4,
    autoUnlock: { type: 'calorie_tracking_days', target: 1 },
  }),
  def({
    id: 'steps_minimum_held',
    title: 'Минимум движения удержан',
    description: 'Несколько дней с минимальным порогом шагов.',
    category: 'endurance',
    goalBands: ALL_BANDS,
    pathTypes: ['mobility_return', 'control_return'],
    unlockMode: 'auto',
    difficulty: 'early',
    tags: ['walk', 'universal', 'beginner'],
    excludedByBaselineEasy: ['walk_10k', 'walk_15k'],
    scoreWeight: 0.4,
    autoUnlock: { type: 'steps_days_minimum', target: 3 },
  }),
  def({
    id: 'clarity_evening_choice',
    title: 'Ясный выбор вечером',
    description: 'Вечерний выбор сделан осознанно, а не на автомате.',
    category: 'alcohol_evening',
    secondaryCategories: ['nutrition_control'],
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['universal', 'evening'],
    scoreWeight: 0.5,
  }),
  def({
    id: 'journal_presence',
    title: 'Строка о теле в дневнике',
    description: 'Появилась честная запись о самочувствии или дне.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['resource_recovery', 'control_return'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['universal', 'journal'],
    scoreWeight: 0.45,
  }),
  def({
    id: 'flexibility_reach',
    title: 'Гибкость в наклоне',
    description: 'Дотянуться или наклониться стало чуть проще.',
    category: 'flexibility',
    goalBands: [...MID, ...DEEP],
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['flex'],
    excludedByBaselineEasy: ['tie_shoes'],
  }),
  def({
    id: 'visible_form_change',
    title: 'Видимое изменение формы',
    description: 'Форма тела заметно сдвинулась — по зеркалу, фото или ощущению.',
    category: 'appearance',
    goalBands: ['20_50', '50_80', '80_plus'],
    pathTypes: ['shape_tuning', 'appearance_focus'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'late',
    tags: ['form'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'new_sport_base',
    title: 'Новая спортивная база',
    description: 'Появилась устойчивая точка возврата к тренировкам.',
    category: 'sport_training',
    goalBands: DEEP,
    pathTypes: ['athlete_return'],
    unlockMode: 'manual',
    difficulty: 'epic',
    tags: ['sport', 'epic'],
    hiddenByTopics: ['sport'],
  }),
  def({
    id: 'mobility_return_felt',
    title: 'Мобильность возвращается',
    description: 'Тело снова легче входит в движение и быт.',
    category: 'mobility',
    goalBands: DEEP,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'epic',
    tags: ['mobility', 'epic', 'functional_limitation'],
    excludedByBaselineEasy: [
      'walk_15k',
      'stairs_ok',
      'stand_from_floor',
      'daily_chores_ok',
    ],
    hiddenByTopics: ['daily_life_limitations'],
  }),
  def({
    id: 'load_reduction_felt',
    title: 'Тело легче несёт свой вес',
    description:
      'Повседневная нагрузка ощущается мягче — как сигнал пути, а не как медицинский вывод.',
    category: 'endurance',
    secondaryCategories: ['daily_life'],
    goalBands: DEEP,
    pathTypes: ['load_reduction', 'athlete_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'epic',
    kind: 'body_change',
    tags: ['load', 'epic'],
  }),
  def({
    id: 'control_rhythm_own',
    title: 'Ритм снова свой',
    description: 'Контроль дня ощущается как опора, а не как давление.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return'],
    unlockMode: 'manual',
    difficulty: 'epic',
    kind: 'route_mastery',
    tags: ['control', 'epic', 'universal'],
    scoreWeight: 0.55,
  }),
  def({
    id: 'clothes_choice_wider',
    title: 'Шире выбор одежды',
    description: 'Появляется чуть больше спокойствия в выборе одежды.',
    category: 'appearance',
    goalBands: SHAPE,
    pathTypes: ['appearance_focus'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['clothes'],
    hiddenByTopics: ['appearance'],
  }),
  def({
    id: 'belt_notch',
    title: 'Ремень на новое деление',
    description: 'Ремень или посадка брюк сдвинулись на заметный шаг.',
    category: 'appearance',
    secondaryCategories: ['measurements'],
    goalBands: [...MID, ...HEAVY],
    pathTypes: ['shape_tuning', 'appearance_focus'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['belt'],
    hiddenByTopics: ['appearance', 'measurements'],
  }),
  def({
    id: 'breath_after_stairs',
    title: 'Дыхание после лестницы спокойнее',
    description: 'После подъёма дыхание выравнивается быстрее.',
    category: 'stairs_routes',
    secondaryCategories: ['endurance'],
    goalBands: HEAVY,
    pathTypes: ['mobility_return'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['stairs', 'breath'],
    excludedByBaselineEasy: ['stairs_ok'],
    hiddenByTopics: ['stairs'],
  }),
  def({
    id: 'morning_rise_easier',
    title: 'Утренний подъём мягче',
    description: 'Вставать утром и входить в день стало чуть проще.',
    category: 'sleep_resource',
    secondaryCategories: ['mobility'],
    goalBands: ALL_BANDS,
    pathTypes: ['resource_recovery', 'mobility_return'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['morning'],
  }),
  def({
    id: 'hydration_rhythm',
    title: 'Ритм питья удерживается',
    description: 'В течение дня вода снова становится привычкой, а не забытым пунктом.',
    category: 'nutrition_control',
    goalBands: LIGHT,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'manual',
    difficulty: 'early',
    tags: ['hydration'],
    hiddenByTopics: ['nutrition'],
  }),
  def({
    id: 'portion_awareness',
    title: 'Порции стали осознаннее',
    description: 'Размер порции выбирается спокойнее, без автоматического «добрать».',
    category: 'nutrition_control',
    goalBands: SHAPE,
    pathTypes: ['control_return', 'shape_tuning'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['portion'],
    hiddenByTopics: ['nutrition'],
  }),
  def({
    id: 'strength_carry',
    title: 'Носить и поднимать проще',
    description: 'Бытовые переносы и подъёмы ощущаются увереннее.',
    category: 'strength',
    secondaryCategories: ['daily_life'],
    goalBands: HEAVY,
    pathTypes: ['athlete_return', 'load_reduction'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    tags: ['carry', 'strength'],
  }),
  def({
    id: 'balance_step',
    title: 'Шаг устойчивее',
    description: 'Уверенность в шаге и равновесии в быту выросла.',
    category: 'mobility',
    secondaryCategories: ['confidence'],
    goalBands: HEAVY,
    pathTypes: ['mobility_return'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['balance'],
  }),
  def({
    id: 'social_move_ease',
    title: 'Проще двигаться среди людей',
    description: 'Прогулка, очередь или событие даются с меньшим напряжением в теле.',
    category: 'confidence',
    goalBands: HEAVY,
    pathTypes: ['appearance_focus', 'mobility_return'],
    unlockMode: 'manual',
    difficulty: 'late',
    tags: ['social', 'confidence'],
  }),
  def({
    id: 'plateau_non_weight_win',
    title: 'Прогресс без движения веса',
    description: 'Даже когда вес стоит, тело отмечает другое улучшение.',
    category: 'confidence',
    goalBands: ALL_BANDS,
    pathTypes: ['control_return', 'resource_recovery'],
    unlockMode: 'manual',
    difficulty: 'middle',
    tags: ['plateau', 'universal'],
    scoreWeight: 0.5,
    hiddenByTopics: ['weight'],
  }),
  def({
    id: 'training_load_recover',
    title: 'Нагрузка и восстановление в паре',
    description:
      'После тренировки или тяжёлого дня восстановление снова становится частью режима.',
    category: 'sport_training',
    secondaryCategories: ['sleep_resource'],
    goalBands: ALL_BANDS,
    pathTypes: ['athlete_return', 'resource_recovery'],
    unlockMode: 'suggested_confirmation',
    difficulty: 'middle',
    kind: 'body_change',
    tags: ['athlete', 'recovery_feel'],
    hiddenByTopics: ['sport'],
  }),
  def({
    id: 'waist_clothes_bridge',
    title: 'Замеры и одежда сходятся',
    description: 'Изменение замеров совпадает с ощущением, что одежда села иначе.',
    category: 'measurements',
    secondaryCategories: ['appearance'],
    goalBands: SHAPE,
    pathTypes: ['shape_tuning', 'appearance_focus'],
    unlockMode: 'manual',
    difficulty: 'middle',
    kind: 'body_change',
    tags: ['waist', 'clothes'],
    hiddenByTopics: ['measurements', 'appearance'],
  }),
];

export const BODY_ABILITY_BANK_BY_ID = Object.fromEntries(
  BODY_ABILITY_BANK.map((a) => [a.id, a]),
) as Record<string, BodyAbilityDefinition>;

export function getBodyAbilityDefinition(id: string): BodyAbilityDefinition | undefined {
  return BODY_ABILITY_BANK_BY_ID[id];
}

export function goalKgToBand(goalKg: number): WeightLossGoalBand {
  if (!Number.isFinite(goalKg) || goalKg < 10) return 'under_10';
  if (goalKg < 20) return '10_20';
  if (goalKg < 50) return '20_50';
  if (goalKg < 80) return '50_80';
  return '80_plus';
}

export const BODY_PATH_TYPE_LABELS: Record<BodyPathType, string> = {
  shape_tuning: 'Собрать форму',
  control_return: 'Вернуть контроль',
  mobility_return: 'Вернуть мобильность',
  athlete_return: 'Вернуть спортивность',
  load_reduction: 'Снизить нагрузку на тело',
  appearance_focus: 'Улучшить внешний вид',
  resource_recovery: 'Восстановить ресурс',
};

export const BODY_INTEREST_LABELS: Record<BodyAbilityInterest, string> = {
  appearance: 'Одежда / силуэт',
  measurements: 'Талия / замеры',
  endurance: 'Выносливость',
  stairs_routes: 'Лестница / маршруты',
  strength: 'Сила',
  flexibility: 'Гибкость / наклоны',
  nutrition_control: 'Контроль питания',
  sleep_resource: 'Сон / ресурс',
  alcohol_evening: 'Алкоголь / вечерний ритм',
  sport_training: 'Спорт / тренировки',
  daily_life: 'Бытовая лёгкость',
  mobility: 'Мобильность',
  confidence: 'Уверенность в движении',
};

export const BODY_BASELINE_LABELS: Record<BodyAbilityBaselineEasy, string> = {
  tie_shoes: 'Завязывать обувь',
  walk_10k: 'Ходить 10 тысяч шагов',
  walk_15k: 'Ходить 15 тысяч шагов',
  stairs_ok: 'Подниматься по лестнице',
  stand_from_floor: 'Вставать с пола',
  stand_long: 'Долго стоять',
  car_ok: 'Ездить в машине',
  daily_chores_ok: 'Делать бытовые дела',
  training_ok: 'Тренироваться',
  nutrition_ok: 'Держать питание',
  alcohol_ok: 'Не пить / контролировать алкоголь',
};

export const BODY_HIDDEN_TOPIC_LABELS: Record<BodyAbilityHiddenTopic, string> = {
  weight: 'Вес',
  alcohol: 'Алкоголь',
  nutrition: 'Питание',
  appearance: 'Внешний вид',
  daily_life_limitations: 'Бытовые ограничения',
  stairs: 'Лестница',
  sport: 'Спорт',
  measurements: 'Замеры',
};

export const BODY_DIFFICULTY_LABELS: Record<BodyAbilityDifficulty, string> = {
  early: 'Ранний этап',
  middle: 'Средний этап',
  late: 'Поздний этап',
  epic: 'Эпический рубеж',
};

export const BODY_UNLOCK_MODE_LABELS: Record<BodyAbilityUnlockMode, string> = {
  auto: 'По данным',
  suggested_confirmation: 'Предложение проверить',
  manual: 'Отметить самому',
};
