import type { BuiltinHabitTemplate } from '../types/habits';
import { SKILL_XP_AWARDS } from './skills';

export const BUILTIN_HABITS: BuiltinHabitTemplate[] = [
  {
    id: 'morningExercise',
    title: 'Зарядка',
    description: 'Утренняя разминка',
    category: 'medium',
    icon: '☀️',
    cardColor: 'warning',
    pointKey: 'morningExercise',
    skillId: 'body',
    skillXpAmount: SKILL_XP_AWARDS.morningExercise,
  },
  {
    id: 'journal',
    title: 'Дневник',
    description: 'Запись в дневник',
    category: 'medium',
    icon: '✍️',
    cardColor: 'secondary',
    pointKey: 'journal',
    skillId: 'clarity',
    skillXpAmount: SKILL_XP_AWARDS.journal,
  },
  {
    id: 'gym',
    title: 'Зал',
    description: 'Тренировка в зале',
    category: 'medium',
    icon: '🏋️',
    cardColor: 'danger',
    pointKey: 'gym',
    skillId: 'body',
    skillXpAmount: SKILL_XP_AWARDS.gym,
  },
  {
    id: 'cooking',
    title: 'Готовка',
    description: 'Приготовил еду',
    category: 'bonus',
    icon: '🍳',
    cardColor: 'primary',
    pointKey: 'cooking',
    skillId: 'home',
    skillXpAmount: SKILL_XP_AWARDS.cooking,
  },
  {
    id: 'repair',
    title: 'Ремонт',
    description: 'Домашние дела',
    category: 'bonus',
    icon: '🔧',
    cardColor: 'default',
    pointKey: 'repair',
    skillId: 'home',
    skillXpAmount: SKILL_XP_AWARDS.repair,
  },
  {
    id: 'plants',
    title: 'Цветы',
    description: 'Уход за растениями',
    category: 'bonus',
    icon: '🌱',
    cardColor: 'success',
    pointKey: 'plants',
    skillId: 'green',
    skillXpAmount: SKILL_XP_AWARDS.plants,
  },
  {
    id: 'hobby',
    title: 'Хобби',
    description: 'Время для себя',
    category: 'bonus',
    icon: '✨',
    cardColor: 'violet',
    pointKey: 'hobby',
    skillId: 'joy',
    skillXpAmount: SKILL_XP_AWARDS.hobby,
  },
];

export const BUILTIN_HABIT_IDS = BUILTIN_HABITS.map((h) => h.id);
