import type { BossDef, BossStatus } from './bossTypes';

const STATUS_DEFAULT: Record<BossStatus, string> = {
  untouched: 'Босс ещё держит территорию.',
  noticed: 'Первые трещины появились.',
  weakened: 'Босс слабеет от удержанного маршрута.',
  broken: 'Его власть заметно ослабла.',
  sealed: 'Сезонная печать почти закрыта.',
};

function seasonBoss(
  seasonId: number,
  title: string,
  shortTitle: string,
  description: string,
  weaknessText: string,
  strengthText: string,
  sources: BossDef['progressSources'],
  flavorLine: string,
  icon: string,
): BossDef {
  return {
    id: `season_mini_${String(seasonId).padStart(2, '0')}`,
    layer: 'seasonMiniBoss',
    seasonId,
    title,
    shortTitle,
    description,
    weaknessText,
    strengthText,
    progressSources: sources,
    flavorLine,
    statusCopy: { ...STATUS_DEFAULT },
    icon,
  };
}

export const SEASON_MINI_BOSSES: BossDef[] = [
  seasonBoss(1, 'Владыка Пустого Дня', 'Пустой день', 'Держит дни без отметок и без маршрута.', 'Ослабевает от сохранённых дней и минимальных ходов.', 'Сильнее, когда день остаётся пустым.', ['seasonQuests', 'routeHeldDays', 'minimalDays'], 'Даже один сохранённый день оставляет трещину.', '👻'),
  seasonBoss(2, 'Диванный Король', 'Диван', 'Притягивает к неподвижности и откладыванию.', 'Отступает от любого движения и шагов.', 'Сильнее без движения.', ['seasonQuests', 'movementDays', 'routeHeldDays'], 'Маршрут не требует героизма — только шаг.', '🛋️'),
  seasonBoss(3, 'Хаос Перекусов', 'Перекусы', 'Размывает контроль дня хаотичным питанием.', 'Рассеивается, когда питание отмечено.', 'Сильнее без учёта питания.', ['seasonQuests', 'nutritionDays', 'routeHeldDays'], 'Отмеченный день — уже удар по хаосу.', '🍪'),
  seasonBoss(4, 'Туманный Барон', 'Туман', 'Скрывает ясность усталостью и туманом.', 'Рассеивается, когда ресурс отмечен.', 'Сильнее, когда ресурс забыт.', ['seasonQuests', 'resourceDays', 'recoveryDays'], 'Ресурс — фонарь в тумане.', '🌫️'),
  seasonBoss(5, 'Пожиратель Ресурса', 'Ресурс', 'Съедает силы быстрее, чем их успевают восполнить.', 'Слабеет от регулярных шагов и движения.', 'Сильнее при хронической усталости.', ['seasonQuests', 'movementDays', 'resourceDays'], 'Шаги возвращают запас сил.', '🔋'),
  seasonBoss(6, 'Страж Перевала', 'Перевал', 'Держит на месте, когда вес стоит.', 'Уступает дням восстановления и удержанию маршрута.', 'Сильнее на плато без маршрута.', ['seasonQuests', 'plateauHolding', 'recoveryDays', 'minimalDays'], 'На перевале маршрут важнее рывка.', '⛰️'),
  seasonBoss(7, 'Цепь Отката', 'Откат', 'Тянет назад после срывов ритма.', 'Рвётся, когда маршрут снова отмечен.', 'Сильнее после пропусков.', ['seasonQuests', 'routeHeldDays', 'minimalDays'], 'Возвращение — уже победа над цепью.', '⛓️'),
  seasonBoss(8, 'Барон Ночного Пира', 'Ночной пир', 'Размывает границы дня ночным перееданием.', 'Ослабевает от ясных дней и трезвости.', 'Сильнее без контроля вечера.', ['seasonQuests', 'nutritionDays', 'alcoholFreeDays'], 'Ясный день — удар по ночному пиру.', '🌙'),
  seasonBoss(9, 'Собиратель Обещаний', 'Обещания', 'Копит невыполненные «с понедельника».', 'Рассыпается от сохранённых дней.', 'Сильнее без отметок.', ['seasonQuests', 'routeHeldDays', 'bodyAbilities'], 'Сохранённый день — обещание, которое сдержано.', '📜'),
  seasonBoss(10, 'Хранитель Старой Формы', 'Старая форма', 'Держит образ прошлого тела.', 'Отступает от движения и зала.', 'Сильнее без движения.', ['seasonQuests', 'movementDays', 'bodyAbilities'], 'Новая форма строится из действий.', '🪞'),
  seasonBoss(11, 'Серый Архивариус Усталости', 'Усталость', 'Архивирует усталость как норму.', 'Меркнет от дневника и трезвых дней.', 'Сильнее без рефлексии.', ['seasonQuests', 'alcoholFreeDays', 'resourceDays'], 'Дневник — свет в сером архиве.', '📚'),
  seasonBoss(12, 'Привратник Новой Мобильности', 'Мобильность', 'Ставит барьер перед новым движением.', 'Уступает, когда путь продолжается.', 'Сильнее при остановке.', ['seasonQuests', 'movementDays', 'bodyAbilities'], 'Каждый шаг — пропуск через привратника.', '🚪'),
  seasonBoss(13, 'Тень Старого Года', 'Старый год', 'Тянет назад к прошлому циклу.', 'Рассеивается, когда маршрут сохранён.', 'Сильнее в конце года без ритма.', ['seasonQuests', 'routeHeldDays', 'campBase'], 'Новый год начинается с удержанного маршрута.', '🌑'),
];

export const CHAPTER_BOSSES: BossDef[] = [
  {
    id: 'chapter_01',
    layer: 'chapterBoss',
    chapterId: 1,
    title: 'Страж Руин',
    shortTitle: 'Страж Руин',
    description: 'Охраняет руины старой привычки не двигаться.',
    weaknessText: 'Он слабеет, когда система возвращается к жизни.',
    strengthText: 'Силён, пока маршрут не зажжён.',
    progressSources: ['routeHeldDays', 'seasonQuests'],
    flavorLine: 'Пробуждение — это не идеал, а возвращение.',
    statusCopy: { ...STATUS_DEFAULT, untouched: 'Страж ещё стоит у руин.' },
    icon: '🏚️',
  },
  {
    id: 'chapter_02',
    layer: 'chapterBoss',
    chapterId: 2,
    title: 'Несущий Груз',
    shortTitle: 'Груз',
    description: 'Тащит тяжесть старых ожиданий.',
    weaknessText: 'Слабеет, когда день отмечен без героизма.',
    strengthText: 'Силён, когда дни пропадают.',
    progressSources: ['routeHeldDays', 'minimalDays'],
    flavorLine: 'Минимальный день снимает часть груза.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🎒',
  },
  {
    id: 'chapter_03',
    layer: 'chapterBoss',
    chapterId: 3,
    title: 'Хозяин Старой Тропы',
    shortTitle: 'Старая тропа',
    description: 'Уводит по привычным следам без прогресса.',
    weaknessText: 'Уступает, когда появляется новый ритм.',
    strengthText: 'Силён без движения.',
    progressSources: ['movementDays', 'routeHeldDays'],
    flavorLine: 'Новая тропа начинается с одного шага.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🛤️',
  },
  {
    id: 'chapter_04',
    layer: 'chapterBoss',
    chapterId: 4,
    title: 'Смотритель Башни Режима',
    shortTitle: 'Башня',
    description: 'Держит режим как клетку, а не опору.',
    weaknessText: 'Слабеет от регулярных отметок и контроля.',
    strengthText: 'Силён при хаосе дня.',
    progressSources: ['nutritionDays', 'routeHeldDays'],
    flavorLine: 'Режим — это опора, не тюрьма.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🗼',
  },
  {
    id: 'chapter_05',
    layer: 'chapterBoss',
    chapterId: 5,
    title: 'Повелитель Тяжёлого Перевала',
    shortTitle: 'Перевал',
    description: 'Делает плато тяжелее, чем оно есть.',
    weaknessText: 'Уступает удержанию маршрута на перевале.',
    strengthText: 'Силён, когда вес стоит без маршрута.',
    progressSources: ['plateauHolding', 'recoveryDays'],
    flavorLine: 'Перевал — не тупик, а участок пути.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '⛰️',
  },
  {
    id: 'chapter_06',
    layer: 'chapterBoss',
    chapterId: 6,
    title: 'Озёрный Хранитель Инерции',
    shortTitle: 'Инерция',
    description: 'Заставляет тонуть в пассивности.',
    weaknessText: 'Слабеет от шагов и движения.',
    strengthText: 'Силён без инерции вперёд.',
    progressSources: ['movementDays', 'resourceDays'],
    flavorLine: 'Движение разбивает озёрную гладь.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🌊',
  },
  {
    id: 'chapter_07',
    layer: 'chapterBoss',
    chapterId: 7,
    title: 'Комендант Крепости Привычек',
    shortTitle: 'Привычки',
    description: 'Обороняет старые паттерны как крепость.',
    weaknessText: 'Слабеет, когда новые дни крепят лагерь.',
    strengthText: 'Силён без устойчивого ритма.',
    progressSources: ['campBase', 'routeHeldDays'],
    flavorLine: 'Лагерь крепнет — привычки меняются.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🏰',
  },
  {
    id: 'chapter_08',
    layer: 'chapterBoss',
    chapterId: 8,
    title: 'Хранитель Реки Движения',
    shortTitle: 'Река',
    description: 'Перекрывает поток движения и энергии.',
    weaknessText: 'Уступает регулярным шагам и залу.',
    strengthText: 'Силён при застое.',
    progressSources: ['movementDays', 'bodyAbilities'],
    flavorLine: 'Река движения снова течёт.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🏞️',
  },
  {
    id: 'chapter_09',
    layer: 'chapterBoss',
    chapterId: 9,
    title: 'Последняя Тень Старой Формы',
    shortTitle: 'Тень',
    description: 'Последний образ того, кем ты был.',
    weaknessText: 'Рассеивается, когда тело возвращает способности.',
    strengthText: 'Силён, пока прогресс виден только в весе.',
    progressSources: ['bodyAbilities', 'seasonQuests', 'campBase'],
    flavorLine: 'Персонаж не стоит — даже когда вес стоит.',
    statusCopy: { ...STATUS_DEFAULT, sealed: 'Тень отступает — путь продолжается.' },
    icon: '👤',
  },
];

export const ACT_BOSSES: BossDef[] = [
  {
    id: 'act_I',
    layer: 'actBoss',
    actId: 'I',
    title: 'Повелитель Хаоса',
    shortTitle: 'Хаос',
    description: 'Акт I — хаос старта и первых попыток.',
    weaknessText: 'Слабеет, когда появляется первый устойчивый ритм.',
    strengthText: 'Силён в хаосе нерегулярных дней.',
    progressSources: ['seasonQuests', 'routeHeldDays'],
    flavorLine: 'Первый акт — зажечь костёр, не сжечь маршрут.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🌀',
  },
  {
    id: 'act_II',
    layer: 'actBoss',
    actId: 'II',
    title: 'Архонт Плато',
    shortTitle: 'Плато',
    description: 'Акт II — долгие участки без видимого веса.',
    weaknessText: 'Уступает не-весовому прогрессу кампании.',
    strengthText: 'Силён, когда виден только вес.',
    progressSources: ['plateauHolding', 'bodyAbilities', 'campBase'],
    flavorLine: 'На плато важны способности, сезон и лагерь.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🏔️',
  },
  {
    id: 'act_III',
    layer: 'actBoss',
    actId: 'III',
    title: 'Хранитель Старой Жизни',
    shortTitle: 'Старая жизнь',
    description: 'Акт III — прощание со старым образом жизни.',
    weaknessText: 'Слабеет, когда новая система держится год.',
    strengthText: 'Силён без долгой устойчивости.',
    progressSources: ['seasonQuests', 'campBase', 'bodyAbilities'],
    flavorLine: 'Новая жизнь — это удержанный маршрут, не один рывок.',
    statusCopy: { ...STATUS_DEFAULT },
    icon: '🕰️',
  },
];

export function getSeasonMiniBossByIndex(seasonIndex: number): BossDef {
  const clamped = Math.min(13, Math.max(1, seasonIndex));
  return SEASON_MINI_BOSSES.find((b) => b.seasonId === clamped) ?? SEASON_MINI_BOSSES[0]!;
}

export function getChapterBossByChapterId(chapterId: number): BossDef | undefined {
  return CHAPTER_BOSSES.find((b) => b.chapterId === chapterId);
}

export function getActBossByActId(actId: 'I' | 'II' | 'III'): BossDef | undefined {
  return ACT_BOSSES.find((b) => b.actId === actId);
}
