import type { SeasonConfig } from './seasonTypes';

const Q = {
  nutrition: (target: number, label?: string) => ({
    id: `nutrition-${target}`,
    type: 'daysWithNutritionTracking' as const,
    target,
    label: label ?? `${target} дней с учётом питания`,
  }),
  steps: (target: number, stepsMin = 5000) => ({
    id: `steps-${target}-${stepsMin}`,
    type: 'daysWithStepsAtLeast' as const,
    target,
    stepsMin,
    label: `${target} дней ${stepsMin.toLocaleString('ru-RU')}+ шагов`,
  }),
  alcohol: (target: number) => ({
    id: `alcohol-${target}`,
    type: 'alcoholFreeDays' as const,
    target,
    label: `${target} дней без алкоголя`,
  }),
  resource: (target: number) => ({
    id: `resource-${target}`,
    type: 'daysWithResourceMarked' as const,
    target,
    label: `${target} дней с отмеченным ресурсом`,
  }),
  minimal: (target: number) => ({
    id: `minimal-${target}`,
    type: 'minimalDaysHeld' as const,
    target,
    label: `${target} минимальных дней`,
  }),
  recovery: (target: number) => ({
    id: `recovery-${target}`,
    type: 'recoveryDays' as const,
    target,
    label: `${target} дней восстановления`,
  }),
  journal: (target: number) => ({
    id: `journal-${target}`,
    type: 'daysWithJournal' as const,
    target,
    label: `${target} дней с дневником`,
  }),
  movement: (target: number) => ({
    id: `movement-${target}`,
    type: 'daysWithMovement' as const,
    target,
    label: `${target} дней с движением`,
  }),
  saved: (target: number) => ({
    id: `saved-${target}`,
    type: 'daysSaved' as const,
    target,
    label: `${target} сохранённых дней`,
  }),
};

export const SEASON_LENGTH_DAYS = 28;
export const SEASON_COUNT = 13;

export const SEASON_CONFIGS: SeasonConfig[] = [
  {
    id: 'spark_in_ruins',
    actId: 'I',
    index: 1,
    title: 'Искра в руинах',
    shortTitle: 'Искра',
    focus: 'зажечь систему без героизма',
    description: 'Не стать идеальным — зажечь костёр, к которому можно вернуться.',
    miniBossName: 'Владыка Пустого Дня',
    miniBossHint: 'слабеет, когда маршрут удержан',
    rewardName: 'Искра ядра',
    quests: [
      Q.nutrition(18),
      Q.steps(14, 5000),
      Q.alcohol(7),
      Q.resource(5),
      Q.minimal(3),
    ],
  },
  {
    id: 'first_tract',
    actId: 'I',
    index: 2,
    title: 'Первый тракт',
    shortTitle: 'Тракт',
    focus: 'первые шаги и ритм',
    description: 'Тропа появляется из повторяемых ходов, а не из рывков.',
    miniBossName: 'Диванный Король',
    miniBossHint: 'отступает от любого движения',
    rewardName: 'Метка тропы',
    quests: [Q.steps(16, 4000), Q.movement(14), Q.saved(10), Q.alcohol(6), Q.journal(4)],
  },
  {
    id: 'stone_base',
    actId: 'I',
    index: 3,
    title: 'Каменная база',
    shortTitle: 'База',
    focus: 'учёт и контроль',
    description: 'Фундамент из честных отметок, а не идеальных недель.',
    miniBossName: 'Хаос Перекусов',
    miniBossHint: 'рассеивается, когда день отмечен',
    rewardName: 'Камень базы',
    quests: [Q.nutrition(20), Q.saved(14), Q.alcohol(8), Q.resource(6), Q.minimal(4)],
  },
  {
    id: 'mode_tower',
    actId: 'I→II',
    index: 4,
    title: 'Башня режима',
    shortTitle: 'Башня',
    focus: 'режим и ресурс',
    description: 'Устойчивый ритм сильнее одного идеального дня.',
    miniBossName: 'Туманный Барон',
    miniBossHint: 'рассеивается, когда ресурс отмечен',
    rewardName: 'Ключ башни',
    quests: [Q.resource(12), Q.recovery(5), Q.nutrition(16), Q.steps(12, 4500), Q.saved(12)],
  },
  {
    id: 'endurance_pass',
    actId: 'II',
    index: 5,
    title: 'Перевал выносливости',
    shortTitle: 'Перевал',
    focus: 'движение и выносливость',
    description: 'Выносливость — это возвращение, а не героизм.',
    miniBossName: 'Пожиратель Ресурса',
    miniBossHint: 'слабеет от регулярных шагов',
    rewardName: 'Перевальная метка',
    quests: [Q.steps(18, 5500), Q.movement(16), Q.alcohol(8), Q.resource(8), Q.saved(14)],
  },
  {
    id: 'recovery_lake',
    actId: 'II',
    index: 6,
    title: 'Озеро восстановления',
    shortTitle: 'Озеро',
    focus: 'отдых и ресурс',
    description: 'Мягкие дни тоже двигают кампанию вперёд.',
    miniBossName: 'Страж Перевала',
    miniBossHint: 'уступает дням восстановления',
    rewardName: 'Озёрный свет',
    quests: [Q.recovery(6), Q.resource(14), Q.minimal(5), Q.saved(12), Q.journal(5)],
  },
  {
    id: 'fortress_stability',
    actId: 'II',
    index: 7,
    title: 'Крепость устойчивости',
    shortTitle: 'Крепость',
    focus: 'удержание привычек',
    description: 'Крепость строится из возвращений, а не из идеала.',
    miniBossName: 'Цепь Отката',
    miniBossHint: 'рвётся, когда маршрут снова отмечен',
    rewardName: 'Печать крепости',
    quests: [Q.saved(18), Q.nutrition(16), Q.alcohol(10), Q.minimal(4), Q.recovery(4)],
  },
  {
    id: 'river_movement',
    actId: 'II',
    index: 8,
    title: 'Река движения',
    shortTitle: 'Река',
    focus: 'шаги и активность',
    description: 'Река течёт из малых ходов каждый день.',
    miniBossName: 'Барон Ночного Пира',
    miniBossHint: 'ослабевает от ясных дней',
    rewardName: 'Капля реки',
    quests: [Q.steps(20, 5000), Q.movement(18), Q.alcohol(9), Q.journal(6), Q.saved(14)],
  },
  {
    id: 'form_citadel',
    actId: 'II→III',
    index: 9,
    title: 'Цитадель формы',
    shortTitle: 'Цитадель',
    focus: 'форма и замеры',
    description: 'Форма — след пути, а не одна цифра на весах.',
    miniBossName: 'Собиратель Обещаний',
    miniBossHint: 'рассыпается от сохранённых дней',
    rewardName: 'Щит формы',
    quests: [Q.saved(20), Q.nutrition(18), Q.steps(14, 5000), Q.resource(10), Q.alcohol(8)],
  },
  {
    id: 'hall_of_strength',
    actId: 'III',
    index: 10,
    title: 'Зал силы',
    shortTitle: 'Зал',
    focus: 'зал и сила',
    description: 'Сила растёт из регулярности, а не из рывка.',
    miniBossName: 'Хранитель Старой Формы',
    miniBossHint: 'отступает от движения и зала',
    rewardName: 'Медаль силы',
    quests: [Q.movement(16), Q.steps(16, 5500), Q.saved(16), Q.resource(8), Q.recovery(4)],
  },
  {
    id: 'clarity_trail',
    actId: 'III',
    index: 11,
    title: 'Тропа ясности',
    shortTitle: 'Ясность',
    focus: 'ясность и трезвость',
    description: 'Ясность — это честные отметки, а не жёсткий контроль.',
    miniBossName: 'Серый Архивариус Усталости',
    miniBossHint: 'меркнет от дневника и трезвых дней',
    rewardName: 'Фонарь ясности',
    quests: [Q.alcohol(12), Q.journal(8), Q.nutrition(16), Q.resource(10), Q.saved(14)],
  },
  {
    id: 'mobility_gates',
    actId: 'III',
    index: 12,
    title: 'Врата новой мобильности',
    shortTitle: 'Врата',
    focus: 'мобильность и движение',
    description: 'Новая мобильность открывается шаг за шагом.',
    miniBossName: 'Привратник Новой Мобильности',
    miniBossHint: 'уступает, когда путь продолжается',
    rewardName: 'Ключ врат',
    quests: [Q.steps(22, 6000), Q.movement(20), Q.saved(18), Q.minimal(5), Q.recovery(5)],
  },
  {
    id: 'year_rebirth',
    actId: 'III',
    index: 13,
    title: 'Перерождение года',
    shortTitle: 'Перерождение',
    focus: 'итог года и новая жизнь',
    description: 'Год — не идеал. Это путь, который ты удержал.',
    miniBossName: 'Тень Старого Года',
    miniBossHint: 'рассеивается, когда маршрут сохранён',
    rewardName: 'Артефакт года',
    quests: [Q.saved(22), Q.nutrition(20), Q.steps(18, 5000), Q.alcohol(12), Q.journal(8)],
  },
];

export function getSeasonConfigByIndex(index: number): SeasonConfig {
  const clamped = Math.min(SEASON_COUNT, Math.max(1, index));
  return SEASON_CONFIGS[clamped - 1]!;
}
