import type { BaseStageDef } from '../../types/baseV1';

export const BASE_STAGES: BaseStageDef[] = [
  {
    id: 'ember',
    level: 1,
    title: 'Тлеющий костёр',
    shortTitle: 'Костёр',
    description: 'Первое место возвращения. Маленький огонь, к которому можно прийти снова.',
    theme: 'ember',
    unlockScore: 0,
    flavorText: 'Костёр ещё мал, но к нему уже можно вернуться.',
    icon: '🔥',
  },
  {
    id: 'shelter',
    level: 2,
    title: 'Укрытие',
    shortTitle: 'Укрытие',
    description: 'Маршрут начал оставлять след — появилось место, где можно передохнуть.',
    theme: 'shelter',
    unlockScore: 25,
    flavorText: 'Маршрут начал оставлять след.',
    icon: '⛺',
  },
  {
    id: 'trail',
    level: 3,
    title: 'Тропа',
    shortTitle: 'Тропа',
    description: 'Путь между днями стал заметнее. Лагерь уже не случайная стоянка.',
    theme: 'trail',
    unlockScore: 60,
    flavorText: 'Тропа ведёт обратно к себе, даже в туманные дни.',
    icon: '🥾',
  },
  {
    id: 'workshop',
    level: 4,
    title: 'Мастерская',
    shortTitle: 'Мастерская',
    description: 'Здесь копится опыт маршрута — не рывками, а повторением.',
    theme: 'workshop',
    unlockScore: 110,
    flavorText: 'Система стала крепче, чем отдельный порыв.',
    icon: '🛠️',
  },
  {
    id: 'clarity',
    level: 5,
    title: 'Башня ясности',
    shortTitle: 'Башня',
    description: 'С высоты видно: прогресс шире, чем одна цифра на весах.',
    theme: 'clarity',
    unlockScore: 175,
    flavorText: 'Ясность приходит не от идеальных дней, а от возвращения.',
    icon: '🗼',
  },
  {
    id: 'hearth',
    level: 6,
    title: 'Очаг восстановления',
    shortTitle: 'Очаг',
    description: 'Место, где можно восстановиться без чувства провала.',
    theme: 'hearth',
    unlockScore: 260,
    flavorText: 'Здесь появляется место, где можно восстановиться.',
    icon: '🕯️',
  },
  {
    id: 'fortress',
    level: 7,
    title: 'Крепость режима',
    shortTitle: 'Крепость',
    description: 'Ритм держится — лагерь стал опорой, а не наградой за вес.',
    theme: 'fortress',
    unlockScore: 370,
    flavorText: 'Режим держится — лагерь крепнет вместе с маршрутом.',
    icon: '🏰',
  },
  {
    id: 'citadel',
    level: 8,
    title: 'Цитадель формы',
    shortTitle: 'Цитадель',
    description: 'Долгий путь оставил след. Лагерь — доказательство, что персонаж не стоит.',
    theme: 'citadel',
    unlockScore: 500,
    flavorText: 'Цитадель формы — не про идеал, а про устойчивость.',
    icon: '👑',
  },
];

export function getBaseStageById(id: string): BaseStageDef | undefined {
  return BASE_STAGES.find((s) => s.id === id);
}
